const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.Flash,
		C3.Behaviors.Platform,
		C3.Behaviors.solid,
		C3.Behaviors.Turret,
		C3.Behaviors.Sin,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Platform.Acts.SimulateControl
	];
};
self.C3_JsPropNameTable = [
	{ceuAzul: 0},
	{fundoEscuro: 0},
	{gramadoVerde: 0},
	{gramadinhoVerde: 0},
	{CentrarEm: 0},
	{Piscar: 0},
	{Plataforma: 0},
	{robotTeen: 0},
	{Sólido: 0},
	{Canhão: 0},
	{Senóide: 0},
	{inimigoAlien: 0},
	{monstrinhoAlien: 0},
	{bandeiraFinal: 0},
	{boxMadeira: 0},
	{cristaisMina: 0},
	{diamanteGrande: 0},
	{moedasRetro: 0},
	{joystic: 0},
	{sensorSolido: 0},
	{Teclado: 0},
	{Âncora: 0},
	{contagemPontosTexto: 0},
	{aprenderConstruct3: 0},
	{vitoria: 0},
	{gameOver: 0},
	{Áudio: 0},
	{esquerdaMobile: 0},
	{direitaMobile: 0},
	{puloMobile: 0},
	{Toque: 0},
	{contadorDePontos: 0}
];

self.InstanceType = {
	ceuAzul: class extends self.ISpriteInstance {},
	fundoEscuro: class extends self.ISpriteInstance {},
	gramadoVerde: class extends self.ISpriteInstance {},
	gramadinhoVerde: class extends self.ISpriteInstance {},
	robotTeen: class extends self.ISpriteInstance {},
	inimigoAlien: class extends self.ISpriteInstance {},
	monstrinhoAlien: class extends self.ISpriteInstance {},
	bandeiraFinal: class extends self.ISpriteInstance {},
	boxMadeira: class extends self.ISpriteInstance {},
	cristaisMina: class extends self.ISpriteInstance {},
	diamanteGrande: class extends self.ISpriteInstance {},
	moedasRetro: class extends self.ISpriteInstance {},
	joystic: class extends self.ISpriteInstance {},
	sensorSolido: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	contagemPontosTexto: class extends self.ITextInstance {},
	aprenderConstruct3: class extends self.ISpriteInstance {},
	vitoria: class extends self.ISpriteInstance {},
	gameOver: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	esquerdaMobile: class extends self.ISpriteInstance {},
	direitaMobile: class extends self.ISpriteInstance {},
	puloMobile: class extends self.ISpriteInstance {},
	Toque: class extends self.IInstance {}
}